version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
  oidc_provider:
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import:ro
    ports:
      - '0.0.0.0:8080:8080/tcp'

volumes:
  db_data: ~
