# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_rating_config_path "./fastlane/metadata/ratings_config.json"

username "konrad.hanus@gmail.com"

submission_information(
  contact_first_name: "Konrad",
  contact_last_name: "Hanus",
  contact_email: "konrad.hanus@gmail.com",
  contact_phone: "+48 669975140" # Use the correct format: '+' followed by the country code and phone number
)