# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "LGLC465F7N",
      issuer_id: "86ecb654-eedc-479b-8a43-9b808278be50",
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true,
    )
    increment_build_number(xcodeproj: "inHEARTive.xcodeproj")
    match(type: "appstore", api_key: api_key)
    build_app(workspace: "inHEARTive.xcworkspace", scheme: "inHEARTive")
    upload_to_app_store(api_key: api_key)
    clean_build_artifacts
  end

  desc "Push a new release build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "LGLC465F7N",
      issuer_id: "86ecb654-eedc-479b-8a43-9b808278be50",
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true,
    )
    increment_build_number(xcodeproj: "inHEARTive.xcodeproj")
    match(type: "appstore", api_key: api_key)
    build_app(workspace: "inHEARTive.xcworkspace", scheme: "inHEARTive")
    upload_to_testflight(api_key: api_key)
    clean_build_artifacts
  end
end
