# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - inheartive-api

on:
  push:
    branches:
      - INHEART-275
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '[**/*.env.prod]'

      - name: Rename .env.prod to .env
        run: |
          mv .env.prod .env

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          yarn install
          yarn nx build backend --prod

      - name: Delete unnecessary items
        run: |
          rm -rf ./apps
          rm -rf ./libs
          rm -rf ./scripts
          rm -rf ./docker
          rm -rf ./apps
          rm -rf ./tools
          rm -rf ./.github
          rm -rf ./.husky
          rm -rf ./.vscode
          rm -rf ./.storybook

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: inheartive-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: inheartive-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'inheartive-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
          package: .
