name: update
on: push

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.10

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Go to frontend directory
        run: ls -al

      - name: Install dependencies
        run: cd ./frontend && npm install

      - name: Publish update
        run: cd ./frontend && eas update --auto

      - name: Build Android
        run: cd ./frontend && eas build --platform android

      - name: Build iOS
        run: cd ./frontend && eas build --platform ios --non-interactive

        #configuration github action with firebase
